### PR TITLE
Update/default numpy

### PR DESCRIPTION
**Pull request by ccoulombe**
Remove the pinned numpy and rely on the `oldest-supported-numpy` module we now have.

### CODE REVIEW

**Comment by ccoulombe** [comment]
@ostueker Any comments on this as well?

**Comment by mboisson** [comment]
That will break whenever `oldest-supported-numpy` is not up to date with the newest version of Python (like right now). I think if we do this, we need to filter the versions of python that we build for. 

Also, could that create issue with existing wheels ? Lots of existing wheels have been built with 1.21.2, but that version is more recent than the oldest supported version for python <3.10

**Comment by mboisson** [comment]
If we load `python-build-bundle`, we should not install/upgrade pip/setuptools&co in the `setup` function

**Comment by ostueker** [comment]
According to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) numpy 1.21 should now be the oldest supported version.

What's the benefit of this over setting `NUMPY_DEFAULT_VERSION=1.22.4` on Jun 23, 2023 (the date to drop support for NumPy 1.21 according to NEP 29)?

**Comment by mboisson** [comment]
> According to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) numpy 1.21 should now be the oldest supported version.
> 
> What's the benefit of this over setting `NUMPY_DEFAULT_VERSION=1.22.4` on Jun 23, 2023 (the date to drop support for NumPy 1.21 according to NEP 29)?

for what it's wort, 1.22.4 is not support for Python 3.11, the oldest supported numpy for python 3.11 is 1.23.2, so that would not work @ostueker

**Comment by ccoulombe** [comment]
> Also, could that create issue with existing wheels ? Lots of existing wheels have been built with 1.21.2, but that version is more recent than the oldest supported version for python <3.10

Yes it could but I think the risk is limited. This applies to newly built wheels from now on. It will also install whatever numpy version other packages may need.

**Comment by mboisson** [comment]
I think this is ready for merging. I have been using this for about a week, rebuilding tons of wheels without major issues

**Review by mboisson — APPROVED** [review]
lgtm

**Comment by ccoulombe** [comment]
Installing the latest `scipy` wheel by default has sneakily been building wheels with the current most recent numpy (1.24).

Since the latest `scipy` needs `numpy<1.27.0,>=1.19.5`, pip installs a `numpy` that is greater than the `oldest-supported-numpy` for the current python, resulting in the wheel's numpy requirement being adjusted to `1.24`.

Removing the `scipy` installation from `PYTHON_DEPS_DEFAULT` effectively fixes this and use the `oldest-supported-numpy` for the current python.

This might create installation issues for some users/wheels.
- Incompatible ABI
- Difficulties in satisfying the `numpy` requirement in a virtual environment.

I've found 17 wheels with a requirements `numpy>=1.24`.

**Pull request merged**
