### PR TITLE
implement a general detection and fix for march=native

### PR DESCRIPTION
**Pull request by mboisson**
This is to address 
https://github.com/ComputeCanada/software-stack/issues/109

### CODE REVIEW

**Review by ccoulombe — CHANGES_REQUESTED** [review]
Looks good! 

The script needs to display a clear message at the end that the wheel should be copied under i.e `avx2`. Otherwise it is easy to miss it and will lead to wheels being built with a target and placed under generic. When it was manually done, it was easy to know.

We should also not remove the set `arch/X` in config when it is needed.

**Comment by mboisson** [comment]
> 

By default, it will be built for `sse3` unless an `arch` module is loaded. If we give that message at the end, people will copy it under `sse3` and it won't be available for `avx2`, even if it would work there too.

**Comment by ccoulombe** [comment]
What I meant is : when `-march=native` is replaced for i.e. `-march=core-avx2`, it need to be explicit at the end of the script that this wheel was built with avx2 instructions and not to be copied under generic as `cp_wheels` would (unless there's libs deps to hint it)

Yes there's an echo, but it is in the middle of many other information so it can be easily missed. At the end of the execution, it is likely to be seen and the wheel copied under the correct folder.

**Comment by ofisette** [comment]
A warning at the end of the build would help for new packages (for updates, existing wheels in arch-specific directories prevent `cp_wheels.sh` from copying to a generic destination). No need to be specific about the arch (i.e. `sse3`), we can use a generic message like we do for `cp_wheels.sh`: “$NAME contains optimised code and must not be copied as a generic wheel. Use cp_wheels.sh --arch <rsnt_arch> to specify the architecture.” Builders who are unsure what this means will ask on Slack.

**Review by ccoulombe — APPROVED** [review]

**Pull request merged**
