### PR TITLE
modified pandas.sh for v0.25.1

### PR DESCRIPTION
**Pull request by sridhar-ravi**
Modified pandas.sh for v0.25.1. Package anvio picky on pandas version.

### CODE REVIEW

**Comment by mboisson** [comment]
Mmm, if anvio is picky, the stricter requirements should be in the `anvio.sh` recipe, not in the `pandas` recipe.

**Review by mboisson — CHANGES_REQUESTED** [review]
pandas itself does not have a strict requirement on a version of numpy. This is not something that should be merged.

**Comment by sridhar-ravi** [comment]
hmmm... bash build_wheel.sh --package pandas --version 0.25.1 --verbose 4 fails. Will look into it again but I am pretty sure.

**Comment by mboisson** [comment]
It built just fine for me ?

**Comment by sridhar-ravi** [comment]
OK ignore this commit. I may have overlooked something.

**Pull request closed without merging**
